# Generated by Django 5.2.10 on 2026-02-27 04:36

import config.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', config.fields.PublicIdField(blank=True, db_index=True, default=config.fields.generate_random_id, help_text='Public-facing random ID', max_length=20, unique=True)),
                ('meditation_id', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('duration_ms', models.PositiveIntegerField()),
                ('timeline', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title', 'meditation_id'],
            },
        ),
    ]
