# Generated by Django 5.2.10 on 2026-02-27 05:00

import config.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeditationAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', config.fields.PublicIdField(blank=True, db_index=True, default=config.fields.generate_random_id, help_text='Public-facing random ID', max_length=20, unique=True)),
                ('audio_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('file', models.FileField(upload_to='meditations/audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['audio_key'],
            },
        ),
    ]
